--liquibase formatted sql
--changeset saliou673:00008-subscription-plan-create-table

CREATE TABLE IF NOT EXISTS subscription_plan
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title            VARCHAR(255)   NOT NULL,
    description      TEXT,
    price            NUMERIC(19, 4) NOT NULL,
    currency_code    VARCHAR(10)    NOT NULL,
    duration_days    INT            NOT NULL,
    active           BOOLEAN        NOT NULL DEFAULT TRUE,
    type             VARCHAR(30)    NOT NULL,
    creation_date    TIMESTAMP      NOT NULL,
    last_update_date TIMESTAMP      NOT NULL,
    last_updated_by  TEXT           NOT NULL,
    CONSTRAINT pk_subscription_plan PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS subscription_plan_feature
(
    plan_id  BIGINT NOT NULL,
    feature  TEXT   NOT NULL,
    position INT    NOT NULL,
    CONSTRAINT pk_subscription_plan_feature PRIMARY KEY (plan_id, position),
    CONSTRAINT fk_subscription_plan_feature_plan FOREIGN KEY (plan_id) REFERENCES subscription_plan (id) ON DELETE CASCADE
);
