--liquibase formatted sql
--changeset saliou673:00014-tax-configuration-create-table

CREATE TABLE IF NOT EXISTS app_tax_configuration
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code             VARCHAR(50)   NOT NULL,
    name             VARCHAR(255)  NOT NULL,
    rate             NUMERIC(10,6) NOT NULL,
    description      TEXT,
    active           BOOLEAN       NOT NULL DEFAULT TRUE,
    creation_date    TIMESTAMP     NOT NULL,
    last_update_date TIMESTAMP     NOT NULL,
    last_updated_by  TEXT          NOT NULL,
    CONSTRAINT pk_app_tax_configuration PRIMARY KEY (id),
    CONSTRAINT un_app_tax_configuration_code UNIQUE (code)
);
