--liquibase formatted sql
--changeset saliou673:00015-enterprise-profile-create-table

CREATE TABLE IF NOT EXISTS app_enterprise_profile
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    company_name        VARCHAR(255) NOT NULL,
    legal_form          VARCHAR(100),
    registration_number VARCHAR(100),
    vat_number          VARCHAR(100),
    address_line1       TEXT,
    address_line2       TEXT,
    city                VARCHAR(100),
    postal_code         VARCHAR(20),
    country_code        CHAR(2),
    phone_number        VARCHAR(50),
    email               VARCHAR(255),
    website             TEXT,
    logo_url            TEXT,
    creation_date       TIMESTAMP    NOT NULL,
    last_update_date    TIMESTAMP    NOT NULL,
    last_updated_by     TEXT         NOT NULL,
    CONSTRAINT pk_app_enterprise_profile PRIMARY KEY (id)
);
