--liquibase formatted sql
--changeset saliou673:00013-storage-settings-create-table

CREATE TABLE IF NOT EXISTS app_storage_settings
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    provider         VARCHAR(50)  NOT NULL,
    bucket_name      TEXT,
    region           TEXT,
    endpoint         TEXT,
    active           BOOLEAN      NOT NULL DEFAULT FALSE,
    creation_date    TIMESTAMP    NOT NULL,
    last_update_date TIMESTAMP    NOT NULL,
    last_updated_by  TEXT         NOT NULL,
    CONSTRAINT pk_app_storage_settings PRIMARY KEY (id)
);
