--liquibase formatted sql
--changeset saliou673:00009-billing-frequency-and-user-subscription

ALTER TABLE subscription_plan
    ALTER COLUMN price DROP NOT NULL,
    ALTER COLUMN duration_days DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS billing_frequency VARCHAR(20) NOT NULL,
    ADD COLUMN IF NOT EXISTS monthly_price     NUMERIC(19, 4),
    ADD COLUMN IF NOT EXISTS yearly_price      NUMERIC(19, 4),
    ADD COLUMN IF NOT EXISTS lifetime_price    NUMERIC(19, 4);

CREATE TABLE IF NOT EXISTS user_subscription
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT         NOT NULL,
    plan_id             BIGINT         NOT NULL,
    plan_title          VARCHAR(255)   NOT NULL,
    price_paid          NUMERIC(19, 4) NOT NULL,
    currency_code       VARCHAR(10)    NOT NULL,
    billing_frequency   VARCHAR(20)    NOT NULL,
    payment_mode        VARCHAR(20)    NOT NULL,
    external_payment_id VARCHAR(255),
    status              VARCHAR(20)    NOT NULL,
    start_date          DATE           NOT NULL,
    end_date            DATE,
    auto_renew          BOOLEAN        NOT NULL,
    creation_date       TIMESTAMP      NOT NULL,
    last_update_date    TIMESTAMP      NOT NULL,
    last_updated_by     TEXT           NOT NULL,
    CONSTRAINT pk_user_subscription PRIMARY KEY (id),
    CONSTRAINT fk_user_subscription_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_subscription_plan FOREIGN KEY (plan_id) REFERENCES subscription_plan (id)
);

CREATE INDEX IF NOT EXISTS idx_user_subscription_user_id ON user_subscription (user_id);
CREATE INDEX IF NOT EXISTS idx_user_subscription_status ON user_subscription (status);
